# Change these first
owner: Domain-Connect # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Domainconnect.org
    url: https://domainconnect.org
  - name: Domainconnect.org example service
    url: https://exampleservice.domainconnect.org/
  - name: Domainconnect.org DynDNS
    url: https://dynamicdns.domainconnect.org/ddnscode?code=test&state=null

assignees:
  - rphilip
  - pawel-kow

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://dynamicdns.domainconnect.org/static/dclogo.png
  name: Domainconnect.org Upptime
  introTitle: "Status of **Domainconnect.org** service websites"
#  introMessage: 
  theme: dark
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
